{% set version = "0.2.2" %}

package:
  name: topika
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/topika/topika-{{ version }}.tar.gz
  sha256: 1be58468850e149e80289cd78cfbdbfd6ff33a8b05d0b119fdbbbee0bb7426c8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tornado >=4.0,<6.0
    - pika >=1.0.0
    - shortuuid
    - six
    - furl
    - future

test:
  imports:
    - topika

about:
  home: https://github.com/aiidateam/topika.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python remote communications library"

extra:
  recipe-maintainers:
  - ltalirz
  - muhrin
  - sphuber
  - chrisjsewell
