{% set version = "0.2.1" %}

package:
  name: topika
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/topika/topika-{{ version }}.tar.gz
  sha256: d73284f34152c687868da188a0fe6ec3ea7ef9c57a8ff1971fa8803f7da9d9f8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tornado >=4.0,<6.0
    - pika >=1.0.0b2
    - pyyaml >=3.0,<4.0
    - shortuuid
    - six
    - furl
    - typing  # [py<35]
    - enum34  # [py<34]
    - singledispatch  # [py<34]
    - mock  # [py<33]
    - backports.tempfile  # [py<32]

test:
  imports:
    - topika

about:
  home: https://github.com/muhrin/topika
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python remote communications library"

extra:
  recipe-maintainers: 
  - ltalirz
  - muhrin
