# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "G218EZA3PjTvWi7ND4fhyheW8lb+ayM5ghorhC3WSwQnuIlKfBt8GBAoT3rpfTnPjjrHX+Pjy0brBvd3Sjhp6O10IQsqqHOOv1vq2GCXuCIkCf8fsgnbsw9fe5EgHJDSPE2+1Aphoffj90GWjkH0vuPy428uhq7TR6X45SmUdA6PHW2xOtOVtsDY711Yot6fg8rodlVptJaJnJw1dfoi5qUDEH7aHHM961v+zwLQ1G+a/kuFaCL6Tl8abpzmZgOkPd2VLbtckJlV/INha6rXot33Zg6Y3u+iwPk+4mx7CQioNh1bbddAMVrqXEdMRk7s+Wa5fq80nYe/cj4/RCFEi/8hJLxGRduNXQDtj7mlfWi92e/sCfWEs/8QY70pgu03mJln3eTxBuL55j2kRd1XLXgGa8v5w9ytZJ4eHWhQerh00d4sAagIrNR5z+0ADi51/EVsrpvTW6TTiz48TJMDrHTshfrJwwjXN0cbhrkBWMi3iuZHkrY9cmP172ul4CtBCZ+WEpj/2dCRmp0KUf07jwB3kyBfuP2L4/6lpfNXcOIjJKKV0mkKjwf5GbTENCk/Wvxu+bndDwWKg+Qmwya/v4NqTjDecbZrpV8VtDj0o8411AtHDbvtYsSZbFsh1fz2U5Qz4lBBqQEj+LWIvOt+UeJeimEvg5pFpp2TJq69V9I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
