travis:
  secure:
    BINSTAR_TOKEN: G218EZA3PjTvWi7ND4fhyheW8lb+ayM5ghorhC3WSwQnuIlKfBt8GBAoT3rpfTnPjjrHX+Pjy0brBvd3Sjhp6O10IQsqqHOOv1vq2GCXuCIkCf8fsgnbsw9fe5EgHJDSPE2+1Aphoffj90GWjkH0vuPy428uhq7TR6X45SmUdA6PHW2xOtOVtsDY711Yot6fg8rodlVptJaJnJw1dfoi5qUDEH7aHHM961v+zwLQ1G+a/kuFaCL6Tl8abpzmZgOkPd2VLbtckJlV/INha6rXot33Zg6Y3u+iwPk+4mx7CQioNh1bbddAMVrqXEdMRk7s+Wa5fq80nYe/cj4/RCFEi/8hJLxGRduNXQDtj7mlfWi92e/sCfWEs/8QY70pgu03mJln3eTxBuL55j2kRd1XLXgGa8v5w9ytZJ4eHWhQerh00d4sAagIrNR5z+0ADi51/EVsrpvTW6TTiz48TJMDrHTshfrJwwjXN0cbhrkBWMi3iuZHkrY9cmP172ul4CtBCZ+WEpj/2dCRmp0KUf07jwB3kyBfuP2L4/6lpfNXcOIjJKKV0mkKjwf5GbTENCk/Wvxu+bndDwWKg+Qmwya/v4NqTjDecbZrpV8VtDj0o8411AtHDbvtYsSZbFsh1fz2U5Qz4lBBqQEj+LWIvOt+UeJeimEvg5pFpp2TJq69V9I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
