appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PuD6piCnH3YvjTJOZXjOVqV35noiJUrHPSn6XPegh7Kj8MmJpuxm8tb/xEZtgLNN1lj/r7cv9x8bzNY1uMtK2mJYJYV3jfd51F1EyC6vWRIgpekbOOTl6ow70qzM/aBeuBWn0kbsd9+5dBr4s+Sg795h1nWELV/1FdZrFs7MtXob1AnzZLDGvgKiJaZAK2fbRQCyg32InsaaL8hJc5IG8GAsMfqFIm6j6VX6d/JbeXKALs/IHbX78P389M/sUTyXJTeH1FeTtDVXnUM1H9KxrUylTlgDLp1S7OAsl7UHSLQRh08DJ7CUAtcUU2VnEdyKl0wRVIyvClNcwTmU2TjZXMvJGHBMlHeyRtaswRBLNIjiMl+9/jx9bCMgy9qM9JxPKGq6EQ3r4BcRF7O6hHdAcj31OEOvq6Yfc3qOmJTL/bBE0uZWgyjiE83eYS0KeUvTHn4iKokex/xVzn8igZKMbWjZO430pYC2Up7mjF1bxmO3AaYZZEjTx65lX2txFd0YExs7W92/yhOmRrjtiou1/wPRGAndjkw9o3a8/6AKLab5Vc10ShfOfP3UWIZygtsG0hQQdBiPyavEJ3CgnqoE9ok/RV0EGHy9EMRZfcjBgRMkeorrmy3CJjwFUOSGLqpS3eCo1lokVA5A9M7x0RPwrRWI02K6YKVcpWqQBfJbtUg=}
provider:
  win: azure
